Create Breadth First Search
soojlee0106/programming-practice pull request #35
Opened 2022-10-24 05:34 UTC by soojlee0106

Grokking Algorithm Chapter 6

2022-10-25 08:01 UTC, syncpark requested changes

2022-10-25 08:01 UTC, syncpark commented on algorithm/src/breadth_first.rs
> +        hashmap.insert("Sally", "seller");
HashMap의 경우 같은 Key로 Insert한 두 번째 값이 이전 값을 덮어쓰는 것으로 알고 있습니다.
```rust
        hashmap.insert("Sally", "Joe");
        hashmap.insert("Sally", "seller");
```
위 코드의 실행 결과로 "Sally" -> "Joe"가 "Sally" -> "seller"로 바뀔겁니다. 아마도!!! 확인해보세요. Hashmap 문서를.

이 테스트 코드는 수정이 필요합니다.

2022-10-25 08:18 UTC, soojlee0106 commented on algorithm/src/breadth_first.rs
> +        hashmap.insert("Sally", "seller");
네, 말씀하신 것이 맞습니다. Key가 겹치지 않도록 테스트 코드를 수정하였습니다.

2022-10-27 00:17 UTC, soojlee0106 commented
Changes: 
1. Match arms used instead of `.is_none()` handling
2. `search` is a hashmap instead of a vector (for optimization)

2022-10-27 01:27 UTC, syncpark requested changes

2022-10-27 01:27 UTC, syncpark commented on algorithm/src/breadth_first.rs
> +        hashmap.insert("Soo", "Sally");
BFS는 Tree 형태의 데이터 구조에서 사용하는 알고리즘이지요. 그런데 샘플로 입력한 데이터는 트리구조가 만들어 지지 않습니다.

Joe -> Bob, Soo -> Sally -> Bob 에서 보면 Bob 위에 2개의 Head가 존재하게 되지요. 이건 Tree 모양을 벗어나게 됩니다.

샘플을 입력하기 전에 Tree 모양으로 먼저 그림을 그려서 데이터를 구성해 보고 입력해보세요.

2022-10-27 04:29 UTC, syncpark commented on algorithm/src/breadth_first.rs
> +        hashmap.insert("Soo", "Sally");
아! 그리고 이런 경우 Hashmap으로는 tree를 만들 수가 없습니다. 다른 하나의 키에 하나의 Value만 저장하니까요!
다만 Value에 Vector를 사용하는 경우라면 가능하겠네요.

2022-10-27 07:16 UTC, soojlee0106 commented on algorithm/src/breadth_first.rs
> +        hashmap.insert("Soo", "Sally");
해당 코멘트를 참조하여 hashmap의 구조를 바꿔 수정하겠습니다.

2022-10-28 01:58 UTC, syncpark approved these changes

2022-10-28 04:13 UTC, merged