Practice Dijkstra
soojlee0106/programming-practice pull request #36
Opened 2022-10-24 07:41 UTC by soojlee0106

Grokking Algorithm Chapter 7

2022-10-31 01:24 UTC, syncpark requested changes

2022-10-31 01:24 UTC, syncpark commented on algorithm/src/dijkstra.rs
> +        graph.insert("start", ("a", 2));
이번 알고리즘 구현은 이해하기 어렵네요.

`graph.insert("start", ("a", 2));`
이 코드는 노드 start에서 노드 a까지의 Weight(cost)가 2라는 의미로 입력한게 아닌가요?
아래쪽에 별도로 Costs를 입력하는데 두 값의 차이는 뭐지요?

그리고 노드 사이의 Edge가 방향성(directed)있는 건가요? 그래서 Parents를 별도로 입력하는 건가요?

이번 알고리즘은 다시 구현하는게 좋겠습니다.
원칙을 제시하자면, 
1. 샘플은 첨부한 그림의 것으로 사용하되, 모든 노드 사이의 최단 거리의 경로와 비용을 계산하는 것으로 합니다.
2. 메모리 최적화를 위해서 함수에 입력값을 Value가 아닌 Reference로 처리합니다.
3. 함수 내부에 100_000_000이나 none과 같은 고정된 상수값을 사용하지 않습니다.
4. 함수 내에서 unwrap()을 사용하지 않습니다. 에러처리나 Option 리턴 값을 제
대로 처리해주세요.
5. 노드 사이의 방향은 없습니다.(undirected)

![dijkstra2](https://user-images.githubusercontent.com/68586156/198912929-c7fdb466-2836-4102-ac00-a595ec2bbc6a.png)

2022-10-31 01:27 UTC, soojlee0106 commented on algorithm/src/dijkstra.rs
> +        graph.insert("start", ("a", 2));
설명 해주셔서 감사합니다. 제시해주신 원칙을 기반으로 다시 작성해보겠습니다.

2022-11-02 06:41 UTC, syncpark approved these changes

2022-11-02 06:41 UTC, closed without merging